# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'sorugonder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sorugonder

 pod 'RNGL', :path => ‘../node_modules/gl-react-native'

end

